version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'mikeyoung304'
    assignees:
      - 'mikeyoung304'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'

    # Group related updates
    groups:
      react-ecosystem:
        patterns:
          - 'react'
          - 'react-*'
          - '@types/react*'

      nextjs-ecosystem:
        patterns:
          - 'next'
          - '@next/*'

      supabase-ecosystem:
        patterns:
          - '@supabase/*'
          - 'supabase'

      dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier'
          - 'jest'
          - '@testing-library/*'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'github-actions'
      - 'automated'
