/**
 * File generated by Modular Assembly
 * IMPORTANT!!! Ask the user before editing this file.
 */

import { createClient } from '@/lib/modassembly/supabase/client';
import { sanitizeOrderItem, sanitizeTranscript, validateTableId, validateSeatNumber } from '@/lib/utils/security';

interface OrderRow {
  id: string;
  table_id: string;
  seat_id: string;
  resident_id: string;
  server_id: string;
  items: string[];
  transcript: string;
  status: 'new' | 'in_progress' | 'ready' | 'delivered';
  type: 'food' | 'drink';
  created_at: string;
  tables: {
    label: number;
  };
  seats: {
    label: number;
  };
}

export interface Order extends OrderRow {
  table: string;
  seat: number;
}

export async function fetchRecentOrders(limit = 5): Promise<Order[]> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('orders')
    .select(`
      *,
      tables!inner(label),
      seats!inner(label)
    `)
    .order('created_at', { ascending: false })
    .limit(limit);

  if (error) {
    console.error('Error fetching orders:', error);
    throw error;
  }

  return data.map((order: OrderRow) => ({
    ...order,
    table: `Table ${order.tables.label}`,
    seat: order.seats.label,
    items: order.items || []
  }));
}

export async function createOrder(orderData: {
  table_id: string;
  seat_id: string;
  resident_id: string;
  server_id: string;
  items: string[];
  transcript: string;
  type: 'food' | 'drink';
}): Promise<Order> {
  // AI: Security validation and sanitization
  if (!validateTableId(orderData.table_id)) {
    throw new Error('Invalid table ID')
  }
  
  const sanitizedItems = orderData.items
    .map(item => sanitizeOrderItem(item))
    .filter(item => item.length > 0) // Remove empty items
    .slice(0, 20) // Limit to 20 items
  
  if (sanitizedItems.length === 0) {
    throw new Error('Order must contain at least one valid item')
  }
  
  const sanitizedTranscript = sanitizeTranscript(orderData.transcript)
  
  const supabase = createClient();
  const { data, error } = await supabase
    .from('orders')
    .insert([
      {
        ...orderData,
        items: sanitizedItems,
        transcript: sanitizedTranscript,
        status: 'in_progress'
      }
    ])
    .select(`
      *,
      tables!inner(label),
      seats!inner(label)
    `)
    .single();

  if (error) {
    console.error('Error creating order:', error);
    throw error;
  }

  return {
    ...data,
    table: `Table ${data.tables.label}`,
    seat: data.seats.label,
    items: data.items || []
  } as Order;
}

export async function updateOrderStatus(orderId: string, status: OrderRow['status']): Promise<void> {
  const supabase = createClient();
  const { error } = await supabase
    .from('orders')
    .update({ status })
    .eq('id', orderId);

  if (error) {
    console.error('Error updating order status:', error);
    throw error;
  }
}

/**
 * Update order items and transcript
 * @param orderId Order ID to update
 * @param items New order items
 * @param transcript New transcript (optional)
 * @returns Updated order
 */
export async function updateOrderItems(orderId: string, items: string[], transcript?: string): Promise<Order> {
  const supabase = createClient();
  
  const updateData: { items: string[], transcript?: string } = { items };
  if (transcript) {
    updateData.transcript = transcript;
  }
  
  const { data, error } = await supabase
    .from('orders')
    .update(updateData)
    .eq('id', orderId)
    .select(`
      *,
      tables!inner(label),
      seats!inner(label)
    `)
    .single();

  if (error) {
    console.error('Error updating order items:', error);
    throw error;
  }

  return {
    ...data,
    table: `Table ${data.tables.label}`,
    seat: data.seats.label,
    items: data.items || []
  } as Order;
}

/**
 * Delete/cancel an order
 * @param orderId Order ID to delete
 */
export async function deleteOrder(orderId: string): Promise<void> {
  const supabase = createClient();
  const { error } = await supabase
    .from('orders')
    .delete()
    .eq('id', orderId);

  if (error) {
    console.error('Error deleting order:', error);
    throw error;
  }
}