/**
 * File generated by Modular Assembly
 * IMPORTANT!!! Ask the user before editing this file.
 *
 * Enterprise Authentication Module - Consolidated Exports
 * Following original developer's modular assembly patterns
 */

// Primary enterprise auth exports (new implementations)
export * from './enterprise-auth-context'
export * from './enterprise-protected-route'
export * from './auth-usage-tracker'
export * from './auth-cache'

// Core auth utilities
export * from './roles'
export * from './client-roles'
export * from './session'

// Backward compatibility - re-export with original names
export { EnterpriseAuthProvider as AuthProvider } from './enterprise-auth-context'
export { ProtectedRoute } from './enterprise-protected-route'

// Legacy auth context (deprecated but kept for compatibility during migration)
export { AuthProvider as LegacyAuthProvider } from './auth-context'
export { ProtectedRoute as LegacyProtectedRoute } from './protected-route'
export { EnhancedProtectedRoute as LegacyEnhancedProtectedRoute } from './enhanced-protected-route'
